# **NumPy Arrays**

In [1]:
import numpy as np
my_list=[1,2,3]

In [2]:
arr=np.array(my_list)

In [3]:
arr

array([1, 2, 3])

In [4]:
matrix_list=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix=np.array(matrix_list)

In [5]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(4)

array([0., 0., 0., 0.])

In [9]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(13)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
#linspace generates evenly spaced numbers over a specified intervals
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.linspace(0,5,10)*12

array([ 0.        ,  6.66666667, 13.33333333, 20.        , 26.66666667,
       33.33333333, 40.        , 46.66666667, 53.33333333, 60.        ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(3)

array([0.23830529, 0.93792233, 0.10947911])

In [21]:
np.random.rand(3,3)

array([[0.82344208, 0.24211713, 0.74213622],
       [0.47753953, 0.24032752, 0.08239251],
       [0.69150442, 0.26968356, 0.2304125 ]])

In [22]:
np.random.randn(4)

array([0.8386154 , 1.65915618, 1.24253964, 0.69361393])

In [23]:
np.random.randn(3,3)

array([[ 0.06353648,  0.0259433 , -0.71244955],
       [ 1.28966404,  0.30972091, -1.04947538],
       [-1.494002  ,  0.85992876,  1.56002157]])

In [24]:
np.random.randint(1,100)

88

In [25]:
np.random.randint(1,100,4)

array([49, 29, 16, 89])

In [26]:
arr=np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr=np.random.randint(0,50,10)

In [29]:
ranarr

array([ 0, 38, 16,  3, 27, 27,  5, 33, 47, 45])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
ranarr.max()

47

In [32]:
ranarr.min()

0

In [33]:
ranarr.argmax()

8

In [34]:
ranarr.argmin()

0

In [35]:
arr.shape

(25,)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
arr=arr.reshape(5,5)

In [40]:
arr.shape

(5, 5)

In [42]:
arr.dtype

dtype('int32')

# **Indexing and Selection**

In [60]:
arr=np.arange(1,25,2)

In [61]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [62]:
arr[3]

7

In [63]:
arr[1:5]

array([3, 5, 7, 9])

In [64]:
arr[::-1]

array([23, 21, 19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [66]:
arr[:6]

array([ 1,  3,  5,  7,  9, 11])

In [67]:
arr[5:]

array([11, 13, 15, 17, 19, 21, 23])

In [68]:
arr[0:5]=100

In [69]:
arr

array([100, 100, 100, 100, 100,  11,  13,  15,  17,  19,  21,  23])